# Generated by Django 2.2.2 on 2019-07-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='total',
            new_name='AMOUNT',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='Item',
            new_name='PRODUCT',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='quantity',
            new_name='QUANTITY',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='unit_price',
            new_name='RATE',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='shipping',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='totals',
        ),
        migrations.AddField(
            model_name='sales',
            name='DESCRIPTION',
            field=models.CharField(default=500, max_length=50),
            preserve_default=False,
        ),
    ]
