# Generated by Django 2.2.2 on 2019-06-21 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=7)),
                ('valid_until', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('phone_number', models.CharField(max_length=12)),
            ],
        ),
    ]
