# Generated by Django 2.2.2 on 2019-07-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotations',
            name='unit_price',
            field=models.IntegerField(),
        ),
    ]
