# Generated by Django 2.2.2 on 2019-07-16 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_auto_20190716_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotations',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='quotations',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='quotations',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='quotations',
            name='valid_until',
        ),
    ]
